// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: product/v1/product.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商品实体（API 返回结构）
type ProductInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId         int64                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ShopName       string                 `protobuf:"bytes,3,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"` // 店铺名称（JOIN 填充）
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,15,opt,name=type,proto3" json:"type,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	MainImageUrl   string                 `protobuf:"bytes,6,opt,name=main_image_url,json=mainImageUrl,proto3" json:"main_image_url,omitempty"`
	Price          int64                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`                                           // 显示分
	CompareAtPrice int64                  `protobuf:"varint,8,opt,name=compare_at_price,json=compareAtPrice,proto3" json:"compare_at_price,omitempty"` // 划线价（分）
	Status         int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`                                         // 0=草稿 1=上架 2=下架
	Sort           int32                  `protobuf:"varint,10,opt,name=sort,proto3" json:"sort,omitempty"`
	TagIds         []int32                `protobuf:"varint,11,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"` // 标签 ID 列表
	TagNames       []string               `protobuf:"bytes,12,rep,name=tag_names,json=tagNames,proto3" json:"tag_names,omitempty"`   // 标签名称列表
	CreatedAt      string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductInfo) Reset() {
	*x = ProductInfo{}
	mi := &file_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfo) ProtoMessage() {}

func (x *ProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfo.ProtoReflect.Descriptor instead.
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductInfo) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ProductInfo) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ProductInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProductInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductInfo) GetMainImageUrl() string {
	if x != nil {
		return x.MainImageUrl
	}
	return ""
}

func (x *ProductInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductInfo) GetCompareAtPrice() int64 {
	if x != nil {
		return x.CompareAtPrice
	}
	return 0
}

func (x *ProductInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProductInfo) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProductInfo) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *ProductInfo) GetTagNames() []string {
	if x != nil {
		return x.TagNames
	}
	return nil
}

func (x *ProductInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProductInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 创建商品
type CreateProductRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShopId         int64                  `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MainImageUrl   string                 `protobuf:"bytes,4,opt,name=main_image_url,json=mainImageUrl,proto3" json:"main_image_url,omitempty"`
	Price          int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	CompareAtPrice int64                  `protobuf:"varint,6,opt,name=compare_at_price,json=compareAtPrice,proto3" json:"compare_at_price,omitempty"`
	Status         int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Sort           int32                  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	TagIds         []int32                `protobuf:"varint,9,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetMainImageUrl() string {
	if x != nil {
		return x.MainImageUrl
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetCompareAtPrice() int64 {
	if x != nil {
		return x.CompareAtPrice
	}
	return 0
}

func (x *CreateProductRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateProductRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateProductRequest) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductInfo           `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_product_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductResponse) GetProduct() *ProductInfo {
	if x != nil {
		return x.Product
	}
	return nil
}

// 更新商品
type UpdateProductRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MainImageUrl   string                 `protobuf:"bytes,4,opt,name=main_image_url,json=mainImageUrl,proto3" json:"main_image_url,omitempty"`
	Price          int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	CompareAtPrice int64                  `protobuf:"varint,6,opt,name=compare_at_price,json=compareAtPrice,proto3" json:"compare_at_price,omitempty"`
	Status         int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Sort           int32                  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	TagIds         []int32                `protobuf:"varint,9,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_product_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetMainImageUrl() string {
	if x != nil {
		return x.MainImageUrl
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetCompareAtPrice() int64 {
	if x != nil {
		return x.CompareAtPrice
	}
	return 0
}

func (x *UpdateProductRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateProductRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UpdateProductRequest) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductInfo           `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_product_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProductResponse) GetProduct() *ProductInfo {
	if x != nil {
		return x.Product
	}
	return nil
}

// 查看商品详情
type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_product_v1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductInfo           `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_product_v1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductResponse) GetProduct() *ProductInfo {
	if x != nil {
		return x.Product
	}
	return nil
}

// 分页查询商品列表
type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码，默认 1
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数，默认 10
	ShopId        int64                  `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`       // 按店铺筛选（0=全部）
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                     // 按状态筛选（-1=全部）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_product_v1_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ListProductsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductInfo         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_product_v1_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{8}
}

func (x *ListProductsResponse) GetProducts() []*ProductInfo {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 删除商品
type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_product_v1_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_product_v1_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_product_v1_product_proto protoreflect.FileDescriptor

const file_product_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x18product/v1/product.proto\x12\n" +
	"product.v1\x1a\x1cgoogle/api/annotations.proto\"\xa3\x03\n" +
	"\vProductInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x03R\x06shopId\x12\x1b\n" +
	"\tshop_name\x18\x03 \x01(\tR\bshopName\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x0f \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12$\n" +
	"\x0emain_image_url\x18\x06 \x01(\tR\fmainImageUrl\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\x12(\n" +
	"\x10compare_at_price\x18\b \x01(\x03R\x0ecompareAtPrice\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x12\n" +
	"\x04sort\x18\n" +
	" \x01(\x05R\x04sort\x12\x17\n" +
	"\atag_ids\x18\v \x03(\x05R\x06tagIds\x12\x1b\n" +
	"\ttag_names\x18\f \x03(\tR\btagNames\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"\xa4\x02\n" +
	"\x14CreateProductRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\x03R\x06shopId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12$\n" +
	"\x0emain_image_url\x18\x04 \x01(\tR\fmainImageUrl\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12(\n" +
	"\x10compare_at_price\x18\x06 \x01(\x03R\x0ecompareAtPrice\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x12\n" +
	"\x04sort\x18\b \x01(\x05R\x04sort\x12\x17\n" +
	"\atag_ids\x18\t \x03(\x05R\x06tagIds\"J\n" +
	"\x15CreateProductResponse\x121\n" +
	"\aproduct\x18\x01 \x01(\v2\x17.product.v1.ProductInfoR\aproduct\"\x9b\x02\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12$\n" +
	"\x0emain_image_url\x18\x04 \x01(\tR\fmainImageUrl\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12(\n" +
	"\x10compare_at_price\x18\x06 \x01(\x03R\x0ecompareAtPrice\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x12\n" +
	"\x04sort\x18\b \x01(\x05R\x04sort\x12\x17\n" +
	"\atag_ids\x18\t \x03(\x05R\x06tagIds\"J\n" +
	"\x15UpdateProductResponse\x121\n" +
	"\aproduct\x18\x01 \x01(\v2\x17.product.v1.ProductInfoR\aproduct\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"G\n" +
	"\x12GetProductResponse\x121\n" +
	"\aproduct\x18\x01 \x01(\v2\x17.product.v1.ProductInfoR\aproduct\"w\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\ashop_id\x18\x03 \x01(\x03R\x06shopId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\x92\x01\n" +
	"\x14ListProductsResponse\x123\n" +
	"\bproducts\x18\x01 \x03(\v2\x17.product.v1.ProductInfoR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\x15DeleteProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc2\x04\n" +
	"\aProduct\x12q\n" +
	"\rCreateProduct\x12 .product.v1.CreateProductRequest\x1a!.product.v1.CreateProductResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/products\x12v\n" +
	"\rUpdateProduct\x12 .product.v1.UpdateProductRequest\x1a!.product.v1.UpdateProductResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/v1/products/{id}\x12j\n" +
	"\n" +
	"GetProduct\x12\x1d.product.v1.GetProductRequest\x1a\x1e.product.v1.GetProductResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/products/{id}\x12k\n" +
	"\fListProducts\x12\x1f.product.v1.ListProductsRequest\x1a .product.v1.ListProductsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/products\x12s\n" +
	"\rDeleteProduct\x12 .product.v1.DeleteProductRequest\x1a!.product.v1.DeleteProductResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/products/{id}B!Z\x1fproductCenter/api/product/v1;v1b\x06proto3"

var (
	file_product_v1_product_proto_rawDescOnce sync.Once
	file_product_v1_product_proto_rawDescData []byte
)

func file_product_v1_product_proto_rawDescGZIP() []byte {
	file_product_v1_product_proto_rawDescOnce.Do(func() {
		file_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_v1_product_proto_rawDesc), len(file_product_v1_product_proto_rawDesc)))
	})
	return file_product_v1_product_proto_rawDescData
}

var file_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_product_v1_product_proto_goTypes = []any{
	(*ProductInfo)(nil),           // 0: product.v1.ProductInfo
	(*CreateProductRequest)(nil),  // 1: product.v1.CreateProductRequest
	(*CreateProductResponse)(nil), // 2: product.v1.CreateProductResponse
	(*UpdateProductRequest)(nil),  // 3: product.v1.UpdateProductRequest
	(*UpdateProductResponse)(nil), // 4: product.v1.UpdateProductResponse
	(*GetProductRequest)(nil),     // 5: product.v1.GetProductRequest
	(*GetProductResponse)(nil),    // 6: product.v1.GetProductResponse
	(*ListProductsRequest)(nil),   // 7: product.v1.ListProductsRequest
	(*ListProductsResponse)(nil),  // 8: product.v1.ListProductsResponse
	(*DeleteProductRequest)(nil),  // 9: product.v1.DeleteProductRequest
	(*DeleteProductResponse)(nil), // 10: product.v1.DeleteProductResponse
}
var file_product_v1_product_proto_depIdxs = []int32{
	0,  // 0: product.v1.CreateProductResponse.product:type_name -> product.v1.ProductInfo
	0,  // 1: product.v1.UpdateProductResponse.product:type_name -> product.v1.ProductInfo
	0,  // 2: product.v1.GetProductResponse.product:type_name -> product.v1.ProductInfo
	0,  // 3: product.v1.ListProductsResponse.products:type_name -> product.v1.ProductInfo
	1,  // 4: product.v1.Product.CreateProduct:input_type -> product.v1.CreateProductRequest
	3,  // 5: product.v1.Product.UpdateProduct:input_type -> product.v1.UpdateProductRequest
	5,  // 6: product.v1.Product.GetProduct:input_type -> product.v1.GetProductRequest
	7,  // 7: product.v1.Product.ListProducts:input_type -> product.v1.ListProductsRequest
	9,  // 8: product.v1.Product.DeleteProduct:input_type -> product.v1.DeleteProductRequest
	2,  // 9: product.v1.Product.CreateProduct:output_type -> product.v1.CreateProductResponse
	4,  // 10: product.v1.Product.UpdateProduct:output_type -> product.v1.UpdateProductResponse
	6,  // 11: product.v1.Product.GetProduct:output_type -> product.v1.GetProductResponse
	8,  // 12: product.v1.Product.ListProducts:output_type -> product.v1.ListProductsResponse
	10, // 13: product.v1.Product.DeleteProduct:output_type -> product.v1.DeleteProductResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_product_v1_product_proto_init() }
func file_product_v1_product_proto_init() {
	if File_product_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_v1_product_proto_rawDesc), len(file_product_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_v1_product_proto_goTypes,
		DependencyIndexes: file_product_v1_product_proto_depIdxs,
		MessageInfos:      file_product_v1_product_proto_msgTypes,
	}.Build()
	File_product_v1_product_proto = out.File
	file_product_v1_product_proto_goTypes = nil
	file_product_v1_product_proto_depIdxs = nil
}
