// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: shop/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_SHOP_UNSPECIFIED ErrorReason = 0
	ErrorReason_SHOP_NOT_FOUND   ErrorReason = 1
	ErrorReason_SHOP_NAME_EMPTY  ErrorReason = 2
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "SHOP_UNSPECIFIED",
		1: "SHOP_NOT_FOUND",
		2: "SHOP_NAME_EMPTY",
	}
	ErrorReason_value = map[string]int32{
		"SHOP_UNSPECIFIED": 0,
		"SHOP_NOT_FOUND":   1,
		"SHOP_NAME_EMPTY":  2,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_shop_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_shop_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_shop_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_shop_v1_error_reason_proto protoreflect.FileDescriptor

const file_shop_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1ashop/v1/error_reason.proto\x12\ashop.v1*L\n" +
	"\vErrorReason\x12\x14\n" +
	"\x10SHOP_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSHOP_NOT_FOUND\x10\x01\x12\x13\n" +
	"\x0fSHOP_NAME_EMPTY\x10\x02B5\n" +
	"\ashop.v1P\x01Z\x1cproductCenter/api/shop/v1;v1\xa2\x02\tAPIShopV1b\x06proto3"

var (
	file_shop_v1_error_reason_proto_rawDescOnce sync.Once
	file_shop_v1_error_reason_proto_rawDescData []byte
)

func file_shop_v1_error_reason_proto_rawDescGZIP() []byte {
	file_shop_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_shop_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_v1_error_reason_proto_rawDesc), len(file_shop_v1_error_reason_proto_rawDesc)))
	})
	return file_shop_v1_error_reason_proto_rawDescData
}

var file_shop_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shop_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: shop.v1.ErrorReason
}
var file_shop_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shop_v1_error_reason_proto_init() }
func file_shop_v1_error_reason_proto_init() {
	if File_shop_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_v1_error_reason_proto_rawDesc), len(file_shop_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shop_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_shop_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_shop_v1_error_reason_proto_enumTypes,
	}.Build()
	File_shop_v1_error_reason_proto = out.File
	file_shop_v1_error_reason_proto_goTypes = nil
	file_shop_v1_error_reason_proto_depIdxs = nil
}
