// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: shop/v1/shop.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 店铺实体
type ShopInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopName      string                 `protobuf:"bytes,2,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopInfo) Reset() {
	*x = ShopInfo{}
	mi := &file_shop_v1_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopInfo) ProtoMessage() {}

func (x *ShopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopInfo.ProtoReflect.Descriptor instead.
func (*ShopInfo) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{0}
}

func (x *ShopInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopInfo) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ShopInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShopInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ShopInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 创建店铺
type CreateShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopName      string                 `protobuf:"bytes,1,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShopRequest) Reset() {
	*x = CreateShopRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShopRequest) ProtoMessage() {}

func (x *CreateShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShopRequest.ProtoReflect.Descriptor instead.
func (*CreateShopRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShopRequest) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *CreateShopRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *ShopInfo              `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShopResponse) Reset() {
	*x = CreateShopResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShopResponse) ProtoMessage() {}

func (x *CreateShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShopResponse.ProtoReflect.Descriptor instead.
func (*CreateShopResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShopResponse) GetShop() *ShopInfo {
	if x != nil {
		return x.Shop
	}
	return nil
}

// 更新店铺
type UpdateShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopName      string                 `protobuf:"bytes,2,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShopRequest) Reset() {
	*x = UpdateShopRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShopRequest) ProtoMessage() {}

func (x *UpdateShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShopRequest.ProtoReflect.Descriptor instead.
func (*UpdateShopRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateShopRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateShopRequest) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *UpdateShopRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *ShopInfo              `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShopResponse) Reset() {
	*x = UpdateShopResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShopResponse) ProtoMessage() {}

func (x *UpdateShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShopResponse.ProtoReflect.Descriptor instead.
func (*UpdateShopResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateShopResponse) GetShop() *ShopInfo {
	if x != nil {
		return x.Shop
	}
	return nil
}

// 查看店铺详情
type GetShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopRequest) Reset() {
	*x = GetShopRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopRequest) ProtoMessage() {}

func (x *GetShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopRequest.ProtoReflect.Descriptor instead.
func (*GetShopRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{5}
}

func (x *GetShopRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *ShopInfo              `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopResponse) Reset() {
	*x = GetShopResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopResponse) ProtoMessage() {}

func (x *GetShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopResponse.ProtoReflect.Descriptor instead.
func (*GetShopResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{6}
}

func (x *GetShopResponse) GetShop() *ShopInfo {
	if x != nil {
		return x.Shop
	}
	return nil
}

// 分页查询店铺列表
type ListShopsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码，默认 1
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数，默认 10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShopsRequest) Reset() {
	*x = ListShopsRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShopsRequest) ProtoMessage() {}

func (x *ListShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShopsRequest.ProtoReflect.Descriptor instead.
func (*ListShopsRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{7}
}

func (x *ListShopsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListShopsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListShopsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shops         []*ShopInfo            `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShopsResponse) Reset() {
	*x = ListShopsResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShopsResponse) ProtoMessage() {}

func (x *ListShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShopsResponse.ProtoReflect.Descriptor instead.
func (*ListShopsResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{8}
}

func (x *ListShopsResponse) GetShops() []*ShopInfo {
	if x != nil {
		return x.Shops
	}
	return nil
}

func (x *ListShopsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListShopsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListShopsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 删除店铺
type DeleteShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShopRequest) Reset() {
	*x = DeleteShopRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShopRequest) ProtoMessage() {}

func (x *DeleteShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShopRequest.ProtoReflect.Descriptor instead.
func (*DeleteShopRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteShopRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShopResponse) Reset() {
	*x = DeleteShopResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShopResponse) ProtoMessage() {}

func (x *DeleteShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShopResponse.ProtoReflect.Descriptor instead.
func (*DeleteShopResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteShopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_shop_v1_shop_proto protoreflect.FileDescriptor

const file_shop_v1_shop_proto_rawDesc = "" +
	"\n" +
	"\x12shop/v1/shop.proto\x12\ashop.v1\x1a\x1cgoogle/api/annotations.proto\"\x97\x01\n" +
	"\bShopInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tshop_name\x18\x02 \x01(\tR\bshopName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"R\n" +
	"\x11CreateShopRequest\x12\x1b\n" +
	"\tshop_name\x18\x01 \x01(\tR\bshopName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\";\n" +
	"\x12CreateShopResponse\x12%\n" +
	"\x04shop\x18\x01 \x01(\v2\x11.shop.v1.ShopInfoR\x04shop\"b\n" +
	"\x11UpdateShopRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tshop_name\x18\x02 \x01(\tR\bshopName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\";\n" +
	"\x12UpdateShopResponse\x12%\n" +
	"\x04shop\x18\x01 \x01(\v2\x11.shop.v1.ShopInfoR\x04shop\" \n" +
	"\x0eGetShopRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\x0fGetShopResponse\x12%\n" +
	"\x04shop\x18\x01 \x01(\v2\x11.shop.v1.ShopInfoR\x04shop\"C\n" +
	"\x10ListShopsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x83\x01\n" +
	"\x11ListShopsResponse\x12'\n" +
	"\x05shops\x18\x01 \x03(\v2\x11.shop.v1.ShopInfoR\x05shops\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"#\n" +
	"\x11DeleteShopRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\".\n" +
	"\x12DeleteShopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe5\x03\n" +
	"\x04Shop\x12_\n" +
	"\n" +
	"CreateShop\x12\x1a.shop.v1.CreateShopRequest\x1a\x1b.shop.v1.CreateShopResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/shops\x12d\n" +
	"\n" +
	"UpdateShop\x12\x1a.shop.v1.UpdateShopRequest\x1a\x1b.shop.v1.UpdateShopResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/shops/{id}\x12X\n" +
	"\aGetShop\x12\x17.shop.v1.GetShopRequest\x1a\x18.shop.v1.GetShopResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/shops/{id}\x12Y\n" +
	"\tListShops\x12\x19.shop.v1.ListShopsRequest\x1a\x1a.shop.v1.ListShopsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/shops\x12a\n" +
	"\n" +
	"DeleteShop\x12\x1a.shop.v1.DeleteShopRequest\x1a\x1b.shop.v1.DeleteShopResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/shops/{id}B\x1eZ\x1cproductCenter/api/shop/v1;v1b\x06proto3"

var (
	file_shop_v1_shop_proto_rawDescOnce sync.Once
	file_shop_v1_shop_proto_rawDescData []byte
)

func file_shop_v1_shop_proto_rawDescGZIP() []byte {
	file_shop_v1_shop_proto_rawDescOnce.Do(func() {
		file_shop_v1_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_v1_shop_proto_rawDesc), len(file_shop_v1_shop_proto_rawDesc)))
	})
	return file_shop_v1_shop_proto_rawDescData
}

var file_shop_v1_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_shop_v1_shop_proto_goTypes = []any{
	(*ShopInfo)(nil),           // 0: shop.v1.ShopInfo
	(*CreateShopRequest)(nil),  // 1: shop.v1.CreateShopRequest
	(*CreateShopResponse)(nil), // 2: shop.v1.CreateShopResponse
	(*UpdateShopRequest)(nil),  // 3: shop.v1.UpdateShopRequest
	(*UpdateShopResponse)(nil), // 4: shop.v1.UpdateShopResponse
	(*GetShopRequest)(nil),     // 5: shop.v1.GetShopRequest
	(*GetShopResponse)(nil),    // 6: shop.v1.GetShopResponse
	(*ListShopsRequest)(nil),   // 7: shop.v1.ListShopsRequest
	(*ListShopsResponse)(nil),  // 8: shop.v1.ListShopsResponse
	(*DeleteShopRequest)(nil),  // 9: shop.v1.DeleteShopRequest
	(*DeleteShopResponse)(nil), // 10: shop.v1.DeleteShopResponse
}
var file_shop_v1_shop_proto_depIdxs = []int32{
	0,  // 0: shop.v1.CreateShopResponse.shop:type_name -> shop.v1.ShopInfo
	0,  // 1: shop.v1.UpdateShopResponse.shop:type_name -> shop.v1.ShopInfo
	0,  // 2: shop.v1.GetShopResponse.shop:type_name -> shop.v1.ShopInfo
	0,  // 3: shop.v1.ListShopsResponse.shops:type_name -> shop.v1.ShopInfo
	1,  // 4: shop.v1.Shop.CreateShop:input_type -> shop.v1.CreateShopRequest
	3,  // 5: shop.v1.Shop.UpdateShop:input_type -> shop.v1.UpdateShopRequest
	5,  // 6: shop.v1.Shop.GetShop:input_type -> shop.v1.GetShopRequest
	7,  // 7: shop.v1.Shop.ListShops:input_type -> shop.v1.ListShopsRequest
	9,  // 8: shop.v1.Shop.DeleteShop:input_type -> shop.v1.DeleteShopRequest
	2,  // 9: shop.v1.Shop.CreateShop:output_type -> shop.v1.CreateShopResponse
	4,  // 10: shop.v1.Shop.UpdateShop:output_type -> shop.v1.UpdateShopResponse
	6,  // 11: shop.v1.Shop.GetShop:output_type -> shop.v1.GetShopResponse
	8,  // 12: shop.v1.Shop.ListShops:output_type -> shop.v1.ListShopsResponse
	10, // 13: shop.v1.Shop.DeleteShop:output_type -> shop.v1.DeleteShopResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_shop_v1_shop_proto_init() }
func file_shop_v1_shop_proto_init() {
	if File_shop_v1_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_v1_shop_proto_rawDesc), len(file_shop_v1_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_v1_shop_proto_goTypes,
		DependencyIndexes: file_shop_v1_shop_proto_depIdxs,
		MessageInfos:      file_shop_v1_shop_proto_msgTypes,
	}.Build()
	File_shop_v1_shop_proto = out.File
	file_shop_v1_shop_proto_goTypes = nil
	file_shop_v1_shop_proto_depIdxs = nil
}
