// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
	"productCenter/internal/biz"
	"productCenter/internal/conf"
	"productCenter/internal/data"
	"productCenter/internal/server"
	"productCenter/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger, registrar registry.Registrar) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	shopRepo := data.NewShopRepo(dataData, logger)
	shopUseCase := biz.NewShopUseCase(shopRepo, logger)
	shopService := service.NewShopService(shopUseCase)
	productRepo := data.NewProductRepo(dataData, logger)
	productUseCase := biz.NewProductUseCase(productRepo, logger)
	productService := service.NewProductService(productUseCase)
	skuRepo := data.NewSkuRepo(dataData, logger)
	skuUseCase := biz.NewSkuUseCase(skuRepo, logger)
	skuService := service.NewSkuService(skuUseCase)
	productTagRepo := data.NewProductTagRepo(dataData, logger)
	productTagUseCase := biz.NewProductTagUseCase(productTagRepo, logger)
	productTagService := service.NewProductTagService(productTagUseCase)
	productMediaRepo := data.NewProductMediaRepo(dataData, logger)
	productMediaUseCase := biz.NewProductMediaUseCase(productMediaRepo, logger)
	productMediaService := service.NewProductMediaService(productMediaUseCase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, shopService, productService, skuService, productTagService, productMediaService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, shopService, productService, skuService, productTagService, productMediaService, logger)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
