// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: bff/v1/bff.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商品详情页聚合数据
type ProductDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId         int64                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ShopName       string                 `protobuf:"bytes,3,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,16,opt,name=type,proto3" json:"type,omitempty"` // 商品主类型
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	MainImageUrl   string                 `protobuf:"bytes,6,opt,name=main_image_url,json=mainImageUrl,proto3" json:"main_image_url,omitempty"`
	Price          int64                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	CompareAtPrice int64                  `protobuf:"varint,8,opt,name=compare_at_price,json=compareAtPrice,proto3" json:"compare_at_price,omitempty"`
	Status         int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	Sort           int32                  `protobuf:"varint,10,opt,name=sort,proto3" json:"sort,omitempty"`
	Tags           []*Tag                 `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`     // 标签列表
	Medias         []*Media               `protobuf:"bytes,12,rep,name=medias,proto3" json:"medias,omitempty"` // 副图列表
	Skus           []*Sku                 `protobuf:"bytes,13,rep,name=skus,proto3" json:"skus,omitempty"`     // SKU 列表
	CreatedAt      string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductDetail) Reset() {
	*x = ProductDetail{}
	mi := &file_bff_v1_bff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDetail) ProtoMessage() {}

func (x *ProductDetail) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDetail.ProtoReflect.Descriptor instead.
func (*ProductDetail) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{0}
}

func (x *ProductDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductDetail) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ProductDetail) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ProductDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProductDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductDetail) GetMainImageUrl() string {
	if x != nil {
		return x.MainImageUrl
	}
	return ""
}

func (x *ProductDetail) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductDetail) GetCompareAtPrice() int64 {
	if x != nil {
		return x.CompareAtPrice
	}
	return 0
}

func (x *ProductDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProductDetail) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProductDetail) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProductDetail) GetMedias() []*Media {
	if x != nil {
		return x.Medias
	}
	return nil
}

func (x *ProductDetail) GetSkus() []*Sku {
	if x != nil {
		return x.Skus
	}
	return nil
}

func (x *ProductDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProductDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_bff_v1_bff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_bff_v1_bff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{2}
}

func (x *Media) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Media) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type Sku struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	ImgUrl        string                 `protobuf:"bytes,6,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sku) Reset() {
	*x = Sku{}
	mi := &file_bff_v1_bff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sku) ProtoMessage() {}

func (x *Sku) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sku.ProtoReflect.Descriptor instead.
func (*Sku) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{3}
}

func (x *Sku) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sku) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Sku) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Sku) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Sku) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Sku) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

// 商品列表项（精简版）
type ProductListItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId         int64                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ShopName       string                 `protobuf:"bytes,3,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"` // 商品主类型
	MainImageUrl   string                 `protobuf:"bytes,5,opt,name=main_image_url,json=mainImageUrl,proto3" json:"main_image_url,omitempty"`
	Price          int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	CompareAtPrice int64                  `protobuf:"varint,7,opt,name=compare_at_price,json=compareAtPrice,proto3" json:"compare_at_price,omitempty"`
	Status         int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Tags           []*Tag                 `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductListItem) Reset() {
	*x = ProductListItem{}
	mi := &file_bff_v1_bff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListItem) ProtoMessage() {}

func (x *ProductListItem) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListItem.ProtoReflect.Descriptor instead.
func (*ProductListItem) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{4}
}

func (x *ProductListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductListItem) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ProductListItem) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ProductListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductListItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProductListItem) GetMainImageUrl() string {
	if x != nil {
		return x.MainImageUrl
	}
	return ""
}

func (x *ProductListItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductListItem) GetCompareAtPrice() int64 {
	if x != nil {
		return x.CompareAtPrice
	}
	return 0
}

func (x *ProductListItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProductListItem) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProductListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 店铺主页数据
type ShopHome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopName      string                 `protobuf:"bytes,2,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Products      []*ProductListItem     `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopHome) Reset() {
	*x = ShopHome{}
	mi := &file_bff_v1_bff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopHome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopHome) ProtoMessage() {}

func (x *ShopHome) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopHome.ProtoReflect.Descriptor instead.
func (*ShopHome) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{5}
}

func (x *ShopHome) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopHome) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ShopHome) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShopHome) GetProducts() []*ProductListItem {
	if x != nil {
		return x.Products
	}
	return nil
}

// 商品详情请求
type GetProductDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductDetailRequest) Reset() {
	*x = GetProductDetailRequest{}
	mi := &file_bff_v1_bff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailRequest) ProtoMessage() {}

func (x *GetProductDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailRequest.ProtoReflect.Descriptor instead.
func (*GetProductDetailRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductDetail         `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductDetailResponse) Reset() {
	*x = GetProductDetailResponse{}
	mi := &file_bff_v1_bff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailResponse) ProtoMessage() {}

func (x *GetProductDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailResponse.ProtoReflect.Descriptor instead.
func (*GetProductDetailResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductDetailResponse) GetProduct() *ProductDetail {
	if x != nil {
		return x.Product
	}
	return nil
}

// 商品列表请求
type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ShopId        int64                  `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_bff_v1_bff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{8}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ListProductsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductListItem     `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_bff_v1_bff_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{9}
}

func (x *ListProductsResponse) GetProducts() []*ProductListItem {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 店铺主页请求
type GetShopHomeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"` // 店铺商品分页
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopHomeRequest) Reset() {
	*x = GetShopHomeRequest{}
	mi := &file_bff_v1_bff_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopHomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopHomeRequest) ProtoMessage() {}

func (x *GetShopHomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopHomeRequest.ProtoReflect.Descriptor instead.
func (*GetShopHomeRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{10}
}

func (x *GetShopHomeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetShopHomeRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetShopHomeRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetShopHomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *ShopHome              `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopHomeResponse) Reset() {
	*x = GetShopHomeResponse{}
	mi := &file_bff_v1_bff_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopHomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopHomeResponse) ProtoMessage() {}

func (x *GetShopHomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_bff_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopHomeResponse.ProtoReflect.Descriptor instead.
func (*GetShopHomeResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_bff_proto_rawDescGZIP(), []int{11}
}

func (x *GetShopHomeResponse) GetShop() *ShopHome {
	if x != nil {
		return x.Shop
	}
	return nil
}

var File_bff_v1_bff_proto protoreflect.FileDescriptor

const file_bff_v1_bff_proto_rawDesc = "" +
	"\n" +
	"\x10bff/v1/bff.proto\x12\x06bff.v1\x1a\x1cgoogle/api/annotations.proto\"\xd8\x03\n" +
	"\rProductDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x03R\x06shopId\x12\x1b\n" +
	"\tshop_name\x18\x03 \x01(\tR\bshopName\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x10 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12$\n" +
	"\x0emain_image_url\x18\x06 \x01(\tR\fmainImageUrl\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\x12(\n" +
	"\x10compare_at_price\x18\b \x01(\x03R\x0ecompareAtPrice\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x12\n" +
	"\x04sort\x18\n" +
	" \x01(\x05R\x04sort\x12\x1f\n" +
	"\x04tags\x18\v \x03(\v2\v.bff.v1.TagR\x04tags\x12%\n" +
	"\x06medias\x18\f \x03(\v2\r.bff.v1.MediaR\x06medias\x12\x1f\n" +
	"\x04skus\x18\r \x03(\v2\v.bff.v1.SkuR\x04skus\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\")\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"=\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\"\x82\x01\n" +
	"\x03Sku\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x17\n" +
	"\aimg_url\x18\x06 \x01(\tR\x06imgUrl\"\xbd\x02\n" +
	"\x0fProductListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x03R\x06shopId\x12\x1b\n" +
	"\tshop_name\x18\x03 \x01(\tR\bshopName\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\v \x01(\tR\x04type\x12$\n" +
	"\x0emain_image_url\x18\x05 \x01(\tR\fmainImageUrl\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12(\n" +
	"\x10compare_at_price\x18\a \x01(\x03R\x0ecompareAtPrice\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1f\n" +
	"\x04tags\x18\t \x03(\v2\v.bff.v1.TagR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\x8e\x01\n" +
	"\bShopHome\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tshop_name\x18\x02 \x01(\tR\bshopName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\bproducts\x18\x04 \x03(\v2\x17.bff.v1.ProductListItemR\bproducts\")\n" +
	"\x17GetProductDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\x18GetProductDetailResponse\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x15.bff.v1.ProductDetailR\aproduct\"w\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\ashop_id\x18\x03 \x01(\x03R\x06shopId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\x92\x01\n" +
	"\x14ListProductsResponse\x123\n" +
	"\bproducts\x18\x01 \x03(\v2\x17.bff.v1.ProductListItemR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"U\n" +
	"\x12GetShopHomeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\";\n" +
	"\x13GetShopHomeResponse\x12$\n" +
	"\x04shop\x18\x01 \x01(\v2\x10.bff.v1.ShopHomeR\x04shop2\xd0\x02\n" +
	"\x03BFF\x12x\n" +
	"\x10GetProductDetail\x12\x1f.bff.v1.GetProductDetailRequest\x1a .bff.v1.GetProductDetailResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/bff/products/{id}\x12g\n" +
	"\fListProducts\x12\x1b.bff.v1.ListProductsRequest\x1a\x1c.bff.v1.ListProductsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/bff/products\x12f\n" +
	"\vGetShopHome\x12\x1a.bff.v1.GetShopHomeRequest\x1a\x1b.bff.v1.GetShopHomeResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/bff/shops/{id}B\x1dZ\x1bproductCenter/api/bff/v1;v1b\x06proto3"

var (
	file_bff_v1_bff_proto_rawDescOnce sync.Once
	file_bff_v1_bff_proto_rawDescData []byte
)

func file_bff_v1_bff_proto_rawDescGZIP() []byte {
	file_bff_v1_bff_proto_rawDescOnce.Do(func() {
		file_bff_v1_bff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bff_v1_bff_proto_rawDesc), len(file_bff_v1_bff_proto_rawDesc)))
	})
	return file_bff_v1_bff_proto_rawDescData
}

var file_bff_v1_bff_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_bff_v1_bff_proto_goTypes = []any{
	(*ProductDetail)(nil),            // 0: bff.v1.ProductDetail
	(*Tag)(nil),                      // 1: bff.v1.Tag
	(*Media)(nil),                    // 2: bff.v1.Media
	(*Sku)(nil),                      // 3: bff.v1.Sku
	(*ProductListItem)(nil),          // 4: bff.v1.ProductListItem
	(*ShopHome)(nil),                 // 5: bff.v1.ShopHome
	(*GetProductDetailRequest)(nil),  // 6: bff.v1.GetProductDetailRequest
	(*GetProductDetailResponse)(nil), // 7: bff.v1.GetProductDetailResponse
	(*ListProductsRequest)(nil),      // 8: bff.v1.ListProductsRequest
	(*ListProductsResponse)(nil),     // 9: bff.v1.ListProductsResponse
	(*GetShopHomeRequest)(nil),       // 10: bff.v1.GetShopHomeRequest
	(*GetShopHomeResponse)(nil),      // 11: bff.v1.GetShopHomeResponse
}
var file_bff_v1_bff_proto_depIdxs = []int32{
	1,  // 0: bff.v1.ProductDetail.tags:type_name -> bff.v1.Tag
	2,  // 1: bff.v1.ProductDetail.medias:type_name -> bff.v1.Media
	3,  // 2: bff.v1.ProductDetail.skus:type_name -> bff.v1.Sku
	1,  // 3: bff.v1.ProductListItem.tags:type_name -> bff.v1.Tag
	4,  // 4: bff.v1.ShopHome.products:type_name -> bff.v1.ProductListItem
	0,  // 5: bff.v1.GetProductDetailResponse.product:type_name -> bff.v1.ProductDetail
	4,  // 6: bff.v1.ListProductsResponse.products:type_name -> bff.v1.ProductListItem
	5,  // 7: bff.v1.GetShopHomeResponse.shop:type_name -> bff.v1.ShopHome
	6,  // 8: bff.v1.BFF.GetProductDetail:input_type -> bff.v1.GetProductDetailRequest
	8,  // 9: bff.v1.BFF.ListProducts:input_type -> bff.v1.ListProductsRequest
	10, // 10: bff.v1.BFF.GetShopHome:input_type -> bff.v1.GetShopHomeRequest
	7,  // 11: bff.v1.BFF.GetProductDetail:output_type -> bff.v1.GetProductDetailResponse
	9,  // 12: bff.v1.BFF.ListProducts:output_type -> bff.v1.ListProductsResponse
	11, // 13: bff.v1.BFF.GetShopHome:output_type -> bff.v1.GetShopHomeResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_bff_v1_bff_proto_init() }
func file_bff_v1_bff_proto_init() {
	if File_bff_v1_bff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bff_v1_bff_proto_rawDesc), len(file_bff_v1_bff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bff_v1_bff_proto_goTypes,
		DependencyIndexes: file_bff_v1_bff_proto_depIdxs,
		MessageInfos:      file_bff_v1_bff_proto_msgTypes,
	}.Build()
	File_bff_v1_bff_proto = out.File
	file_bff_v1_bff_proto_goTypes = nil
	file_bff_v1_bff_proto_depIdxs = nil
}
