name: gateway

endpoints:
  # BFF：/api/v1/bff/* 透传到 bff:8002
  - path: /api/v1/bff/*
    method: "*"
    protocol: HTTP
    backends:
      - target: "127.0.0.1:8002"
        weight: 100
    timeout: 5s
    middlewares:
      - name: cors
      - name: logging
      - name: tracing
      - name: transcoder
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio:
            success: 0.5
            request: 10
            bucket: 10
            window: 10s
      - name: bbr

  # Order：/api/v1/orders* 透传到 order:8001
  - path: /api/v1/orders*
    method: "*"
    protocol: HTTP
    backends:
      - target: "127.0.0.1:8001"
        weight: 100
    timeout: 5s
    middlewares:
      - name: cors
      - name: logging
      - name: tracing
      - name: transcoder
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio:
            success: 0.5
            request: 10
            bucket: 10
            window: 10s
      - name: bbr

  # ProductCenter：/api/v1/* 透传到 productCenter:8000
  - path: /api/v1/*
    method: "*"
    protocol: HTTP
    backends:
      - target: "127.0.0.1:8000"
        weight: 100
    timeout: 5s
    middlewares:
      - name: cors
      - name: logging
      - name: tracing
      - name: transcoder
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio:
            success: 0.5
            request: 10
            bucket: 10
            window: 10s
      - name: bbr
