// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: productmedia/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_PRODUCT_MEDIA_UNSPECIFIED        ErrorReason = 0
	ErrorReason_PRODUCT_MEDIA_NOT_FOUND          ErrorReason = 1
	ErrorReason_PRODUCT_MEDIA_PRODUCT_ID_INVALID ErrorReason = 2
	ErrorReason_PRODUCT_MEDIA_URL_EMPTY          ErrorReason = 3
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "PRODUCT_MEDIA_UNSPECIFIED",
		1: "PRODUCT_MEDIA_NOT_FOUND",
		2: "PRODUCT_MEDIA_PRODUCT_ID_INVALID",
		3: "PRODUCT_MEDIA_URL_EMPTY",
	}
	ErrorReason_value = map[string]int32{
		"PRODUCT_MEDIA_UNSPECIFIED":        0,
		"PRODUCT_MEDIA_NOT_FOUND":          1,
		"PRODUCT_MEDIA_PRODUCT_ID_INVALID": 2,
		"PRODUCT_MEDIA_URL_EMPTY":          3,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_productmedia_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_productmedia_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_productmedia_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_productmedia_v1_error_reason_proto protoreflect.FileDescriptor

const file_productmedia_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\"productmedia/v1/error_reason.proto\x12\x0fproductmedia.v1*\x8c\x01\n" +
	"\vErrorReason\x12\x1d\n" +
	"\x19PRODUCT_MEDIA_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PRODUCT_MEDIA_NOT_FOUND\x10\x01\x12$\n" +
	" PRODUCT_MEDIA_PRODUCT_ID_INVALID\x10\x02\x12\x1b\n" +
	"\x17PRODUCT_MEDIA_URL_EMPTY\x10\x03BM\n" +
	"\x0fproductmedia.v1P\x01Z$productCenter/api/productmedia/v1;v1\xa2\x02\x11APIProductMediaV1b\x06proto3"

var (
	file_productmedia_v1_error_reason_proto_rawDescOnce sync.Once
	file_productmedia_v1_error_reason_proto_rawDescData []byte
)

func file_productmedia_v1_error_reason_proto_rawDescGZIP() []byte {
	file_productmedia_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_productmedia_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_productmedia_v1_error_reason_proto_rawDesc), len(file_productmedia_v1_error_reason_proto_rawDesc)))
	})
	return file_productmedia_v1_error_reason_proto_rawDescData
}

var file_productmedia_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_productmedia_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: productmedia.v1.ErrorReason
}
var file_productmedia_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_productmedia_v1_error_reason_proto_init() }
func file_productmedia_v1_error_reason_proto_init() {
	if File_productmedia_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_productmedia_v1_error_reason_proto_rawDesc), len(file_productmedia_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_productmedia_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_productmedia_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_productmedia_v1_error_reason_proto_enumTypes,
	}.Build()
	File_productmedia_v1_error_reason_proto = out.File
	file_productmedia_v1_error_reason_proto_goTypes = nil
	file_productmedia_v1_error_reason_proto_depIdxs = nil
}
