// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: productmedia/v1/product_media.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductMedia_CreateMedia_FullMethodName = "/productmedia.v1.ProductMedia/CreateMedia"
	ProductMedia_UpdateMedia_FullMethodName = "/productmedia.v1.ProductMedia/UpdateMedia"
	ProductMedia_GetMedia_FullMethodName    = "/productmedia.v1.ProductMedia/GetMedia"
	ProductMedia_ListMedias_FullMethodName  = "/productmedia.v1.ProductMedia/ListMedias"
	ProductMedia_DeleteMedia_FullMethodName = "/productmedia.v1.ProductMedia/DeleteMedia"
)

// ProductMediaClient is the client API for ProductMedia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 商品副图服务
type ProductMediaClient interface {
	// 上传副图（创建）
	CreateMedia(ctx context.Context, in *CreateMediaRequest, opts ...grpc.CallOption) (*CreateMediaResponse, error)
	// 更新副图
	UpdateMedia(ctx context.Context, in *UpdateMediaRequest, opts ...grpc.CallOption) (*UpdateMediaResponse, error)
	// 查看副图详情
	GetMedia(ctx context.Context, in *GetMediaRequest, opts ...grpc.CallOption) (*GetMediaResponse, error)
	// 分页查询副图列表（支持按商品筛选）
	ListMedias(ctx context.Context, in *ListMediasRequest, opts ...grpc.CallOption) (*ListMediasResponse, error)
	// 删除副图
	DeleteMedia(ctx context.Context, in *DeleteMediaRequest, opts ...grpc.CallOption) (*DeleteMediaResponse, error)
}

type productMediaClient struct {
	cc grpc.ClientConnInterface
}

func NewProductMediaClient(cc grpc.ClientConnInterface) ProductMediaClient {
	return &productMediaClient{cc}
}

func (c *productMediaClient) CreateMedia(ctx context.Context, in *CreateMediaRequest, opts ...grpc.CallOption) (*CreateMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMediaResponse)
	err := c.cc.Invoke(ctx, ProductMedia_CreateMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productMediaClient) UpdateMedia(ctx context.Context, in *UpdateMediaRequest, opts ...grpc.CallOption) (*UpdateMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMediaResponse)
	err := c.cc.Invoke(ctx, ProductMedia_UpdateMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productMediaClient) GetMedia(ctx context.Context, in *GetMediaRequest, opts ...grpc.CallOption) (*GetMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMediaResponse)
	err := c.cc.Invoke(ctx, ProductMedia_GetMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productMediaClient) ListMedias(ctx context.Context, in *ListMediasRequest, opts ...grpc.CallOption) (*ListMediasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMediasResponse)
	err := c.cc.Invoke(ctx, ProductMedia_ListMedias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productMediaClient) DeleteMedia(ctx context.Context, in *DeleteMediaRequest, opts ...grpc.CallOption) (*DeleteMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMediaResponse)
	err := c.cc.Invoke(ctx, ProductMedia_DeleteMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductMediaServer is the server API for ProductMedia service.
// All implementations must embed UnimplementedProductMediaServer
// for forward compatibility.
//
// 商品副图服务
type ProductMediaServer interface {
	// 上传副图（创建）
	CreateMedia(context.Context, *CreateMediaRequest) (*CreateMediaResponse, error)
	// 更新副图
	UpdateMedia(context.Context, *UpdateMediaRequest) (*UpdateMediaResponse, error)
	// 查看副图详情
	GetMedia(context.Context, *GetMediaRequest) (*GetMediaResponse, error)
	// 分页查询副图列表（支持按商品筛选）
	ListMedias(context.Context, *ListMediasRequest) (*ListMediasResponse, error)
	// 删除副图
	DeleteMedia(context.Context, *DeleteMediaRequest) (*DeleteMediaResponse, error)
	mustEmbedUnimplementedProductMediaServer()
}

// UnimplementedProductMediaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductMediaServer struct{}

func (UnimplementedProductMediaServer) CreateMedia(context.Context, *CreateMediaRequest) (*CreateMediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMedia not implemented")
}
func (UnimplementedProductMediaServer) UpdateMedia(context.Context, *UpdateMediaRequest) (*UpdateMediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMedia not implemented")
}
func (UnimplementedProductMediaServer) GetMedia(context.Context, *GetMediaRequest) (*GetMediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedia not implemented")
}
func (UnimplementedProductMediaServer) ListMedias(context.Context, *ListMediasRequest) (*ListMediasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMedias not implemented")
}
func (UnimplementedProductMediaServer) DeleteMedia(context.Context, *DeleteMediaRequest) (*DeleteMediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMedia not implemented")
}
func (UnimplementedProductMediaServer) mustEmbedUnimplementedProductMediaServer() {}
func (UnimplementedProductMediaServer) testEmbeddedByValue()                      {}

// UnsafeProductMediaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductMediaServer will
// result in compilation errors.
type UnsafeProductMediaServer interface {
	mustEmbedUnimplementedProductMediaServer()
}

func RegisterProductMediaServer(s grpc.ServiceRegistrar, srv ProductMediaServer) {
	// If the following call pancis, it indicates UnimplementedProductMediaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductMedia_ServiceDesc, srv)
}

func _ProductMedia_CreateMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductMediaServer).CreateMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductMedia_CreateMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductMediaServer).CreateMedia(ctx, req.(*CreateMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductMedia_UpdateMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductMediaServer).UpdateMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductMedia_UpdateMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductMediaServer).UpdateMedia(ctx, req.(*UpdateMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductMedia_GetMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductMediaServer).GetMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductMedia_GetMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductMediaServer).GetMedia(ctx, req.(*GetMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductMedia_ListMedias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMediasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductMediaServer).ListMedias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductMedia_ListMedias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductMediaServer).ListMedias(ctx, req.(*ListMediasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductMedia_DeleteMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductMediaServer).DeleteMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductMedia_DeleteMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductMediaServer).DeleteMedia(ctx, req.(*DeleteMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductMedia_ServiceDesc is the grpc.ServiceDesc for ProductMedia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductMedia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "productmedia.v1.ProductMedia",
	HandlerType: (*ProductMediaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMedia",
			Handler:    _ProductMedia_CreateMedia_Handler,
		},
		{
			MethodName: "UpdateMedia",
			Handler:    _ProductMedia_UpdateMedia_Handler,
		},
		{
			MethodName: "GetMedia",
			Handler:    _ProductMedia_GetMedia_Handler,
		},
		{
			MethodName: "ListMedias",
			Handler:    _ProductMedia_ListMedias_Handler,
		},
		{
			MethodName: "DeleteMedia",
			Handler:    _ProductMedia_DeleteMedia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "productmedia/v1/product_media.proto",
}
