// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: productmedia/v1/product_media.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 副图实体
type MediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`    // 图片URL
	Sort          int64                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"` // 排序
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaInfo) Reset() {
	*x = MediaInfo{}
	mi := &file_productmedia_v1_product_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaInfo) ProtoMessage() {}

func (x *MediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_productmedia_v1_product_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaInfo.ProtoReflect.Descriptor instead.
func (*MediaInfo) Descriptor() ([]byte, []int) {
	return file_productmedia_v1_product_media_proto_rawDescGZIP(), []int{0}
}

func (x *MediaInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MediaInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *MediaInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaInfo) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *MediaInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MediaInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 创建副图
type CreateMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Sort          int64                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMediaRequest) Reset() {
	*x = CreateMediaRequest{}
	mi := &file_productmedia_v1_product_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaRequest) ProtoMessage() {}

func (x *CreateMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_productmedia_v1_product_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaRequest.ProtoReflect.Descriptor instead.
func (*CreateMediaRequest) Descriptor() ([]byte, []int) {
	return file_productmedia_v1_product_media_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMediaRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateMediaRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateMediaRequest) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type CreateMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaInfo             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMediaResponse) Reset() {
	*x = CreateMediaResponse{}
	mi := &file_productmedia_v1_product_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaResponse) ProtoMessage() {}

func (x *CreateMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_productmedia_v1_product_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaResponse.ProtoReflect.Descriptor instead.
func (*CreateMediaResponse) Descriptor() ([]byte, []int) {
	return file_productmedia_v1_product_media_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMediaResponse) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

// 更新副图
type UpdateMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Sort          int64                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMediaRequest) Reset() {
	*x = UpdateMediaRequest{}
	mi := &file_productmedia_v1_product_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaRequest) ProtoMessage() {}

func (x *UpdateMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_productmedia_v1_product_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaRequest.ProtoReflect.Descriptor instead.
func (*UpdateMediaRequest) Descriptor() ([]byte, []int) {
	return file_productmedia_v1_product_media_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMediaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMediaRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateMediaRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateMediaRequest) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type UpdateMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaInfo             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMediaResponse) Reset() {
	*x = UpdateMediaResponse{}
	mi := &file_productmedia_v1_product_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaResponse) ProtoMessage() {}

func (x *UpdateMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_productmedia_v1_product_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaResponse.ProtoReflect.Descriptor instead.
func (*UpdateMediaResponse) Descriptor() ([]byte, []int) {
	return file_productmedia_v1_product_media_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMediaResponse) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

// 查看副图详情
type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_productmedia_v1_product_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_productmedia_v1_product_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_productmedia_v1_product_media_proto_rawDescGZIP(), []int{5}
}

func (x *GetMediaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaInfo             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	mi := &file_productmedia_v1_product_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_productmedia_v1_product_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_productmedia_v1_product_media_proto_rawDescGZIP(), []int{6}
}

func (x *GetMediaResponse) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

// 分页查询副图列表
type ListMediasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                            // 页码，默认 1
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`    // 每页条数，默认 10
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // 按商品筛选（0=全部）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediasRequest) Reset() {
	*x = ListMediasRequest{}
	mi := &file_productmedia_v1_product_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediasRequest) ProtoMessage() {}

func (x *ListMediasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_productmedia_v1_product_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediasRequest.ProtoReflect.Descriptor instead.
func (*ListMediasRequest) Descriptor() ([]byte, []int) {
	return file_productmedia_v1_product_media_proto_rawDescGZIP(), []int{7}
}

func (x *ListMediasRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMediasRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMediasRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ListMediasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medias        []*MediaInfo           `protobuf:"bytes,1,rep,name=medias,proto3" json:"medias,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediasResponse) Reset() {
	*x = ListMediasResponse{}
	mi := &file_productmedia_v1_product_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediasResponse) ProtoMessage() {}

func (x *ListMediasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_productmedia_v1_product_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediasResponse.ProtoReflect.Descriptor instead.
func (*ListMediasResponse) Descriptor() ([]byte, []int) {
	return file_productmedia_v1_product_media_proto_rawDescGZIP(), []int{8}
}

func (x *ListMediasResponse) GetMedias() []*MediaInfo {
	if x != nil {
		return x.Medias
	}
	return nil
}

func (x *ListMediasResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMediasResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMediasResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 删除副图
type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_productmedia_v1_product_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_productmedia_v1_product_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_productmedia_v1_product_media_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMediaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResponse) Reset() {
	*x = DeleteMediaResponse{}
	mi := &file_productmedia_v1_product_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResponse) ProtoMessage() {}

func (x *DeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_productmedia_v1_product_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_productmedia_v1_product_media_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMediaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_productmedia_v1_product_media_proto protoreflect.FileDescriptor

const file_productmedia_v1_product_media_proto_rawDesc = "" +
	"\n" +
	"#productmedia/v1/product_media.proto\x12\x0fproductmedia.v1\x1a\x1cgoogle/api/annotations.proto\"\x9e\x01\n" +
	"\tMediaInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x03R\x04sort\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"Y\n" +
	"\x12CreateMediaRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x03R\x04sort\"G\n" +
	"\x13CreateMediaResponse\x120\n" +
	"\x05media\x18\x01 \x01(\v2\x1a.productmedia.v1.MediaInfoR\x05media\"i\n" +
	"\x12UpdateMediaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x03R\x04sort\"G\n" +
	"\x13UpdateMediaResponse\x120\n" +
	"\x05media\x18\x01 \x01(\v2\x1a.productmedia.v1.MediaInfoR\x05media\"!\n" +
	"\x0fGetMediaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"D\n" +
	"\x10GetMediaResponse\x120\n" +
	"\x05media\x18\x01 \x01(\v2\x1a.productmedia.v1.MediaInfoR\x05media\"c\n" +
	"\x11ListMediasRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\"\x8f\x01\n" +
	"\x12ListMediasResponse\x122\n" +
	"\x06medias\x18\x01 \x03(\v2\x1a.productmedia.v1.MediaInfoR\x06medias\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"$\n" +
	"\x12DeleteMediaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x13DeleteMediaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf4\x04\n" +
	"\fProductMedia\x12z\n" +
	"\vCreateMedia\x12#.productmedia.v1.CreateMediaRequest\x1a$.productmedia.v1.CreateMediaResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/product-media\x12\x7f\n" +
	"\vUpdateMedia\x12#.productmedia.v1.UpdateMediaRequest\x1a$.productmedia.v1.UpdateMediaResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/api/v1/product-media/{id}\x12s\n" +
	"\bGetMedia\x12 .productmedia.v1.GetMediaRequest\x1a!.productmedia.v1.GetMediaResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/product-media/{id}\x12t\n" +
	"\n" +
	"ListMedias\x12\".productmedia.v1.ListMediasRequest\x1a#.productmedia.v1.ListMediasResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/product-media\x12|\n" +
	"\vDeleteMedia\x12#.productmedia.v1.DeleteMediaRequest\x1a$.productmedia.v1.DeleteMediaResponse\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v1/product-media/{id}B&Z$productCenter/api/productmedia/v1;v1b\x06proto3"

var (
	file_productmedia_v1_product_media_proto_rawDescOnce sync.Once
	file_productmedia_v1_product_media_proto_rawDescData []byte
)

func file_productmedia_v1_product_media_proto_rawDescGZIP() []byte {
	file_productmedia_v1_product_media_proto_rawDescOnce.Do(func() {
		file_productmedia_v1_product_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_productmedia_v1_product_media_proto_rawDesc), len(file_productmedia_v1_product_media_proto_rawDesc)))
	})
	return file_productmedia_v1_product_media_proto_rawDescData
}

var file_productmedia_v1_product_media_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_productmedia_v1_product_media_proto_goTypes = []any{
	(*MediaInfo)(nil),           // 0: productmedia.v1.MediaInfo
	(*CreateMediaRequest)(nil),  // 1: productmedia.v1.CreateMediaRequest
	(*CreateMediaResponse)(nil), // 2: productmedia.v1.CreateMediaResponse
	(*UpdateMediaRequest)(nil),  // 3: productmedia.v1.UpdateMediaRequest
	(*UpdateMediaResponse)(nil), // 4: productmedia.v1.UpdateMediaResponse
	(*GetMediaRequest)(nil),     // 5: productmedia.v1.GetMediaRequest
	(*GetMediaResponse)(nil),    // 6: productmedia.v1.GetMediaResponse
	(*ListMediasRequest)(nil),   // 7: productmedia.v1.ListMediasRequest
	(*ListMediasResponse)(nil),  // 8: productmedia.v1.ListMediasResponse
	(*DeleteMediaRequest)(nil),  // 9: productmedia.v1.DeleteMediaRequest
	(*DeleteMediaResponse)(nil), // 10: productmedia.v1.DeleteMediaResponse
}
var file_productmedia_v1_product_media_proto_depIdxs = []int32{
	0,  // 0: productmedia.v1.CreateMediaResponse.media:type_name -> productmedia.v1.MediaInfo
	0,  // 1: productmedia.v1.UpdateMediaResponse.media:type_name -> productmedia.v1.MediaInfo
	0,  // 2: productmedia.v1.GetMediaResponse.media:type_name -> productmedia.v1.MediaInfo
	0,  // 3: productmedia.v1.ListMediasResponse.medias:type_name -> productmedia.v1.MediaInfo
	1,  // 4: productmedia.v1.ProductMedia.CreateMedia:input_type -> productmedia.v1.CreateMediaRequest
	3,  // 5: productmedia.v1.ProductMedia.UpdateMedia:input_type -> productmedia.v1.UpdateMediaRequest
	5,  // 6: productmedia.v1.ProductMedia.GetMedia:input_type -> productmedia.v1.GetMediaRequest
	7,  // 7: productmedia.v1.ProductMedia.ListMedias:input_type -> productmedia.v1.ListMediasRequest
	9,  // 8: productmedia.v1.ProductMedia.DeleteMedia:input_type -> productmedia.v1.DeleteMediaRequest
	2,  // 9: productmedia.v1.ProductMedia.CreateMedia:output_type -> productmedia.v1.CreateMediaResponse
	4,  // 10: productmedia.v1.ProductMedia.UpdateMedia:output_type -> productmedia.v1.UpdateMediaResponse
	6,  // 11: productmedia.v1.ProductMedia.GetMedia:output_type -> productmedia.v1.GetMediaResponse
	8,  // 12: productmedia.v1.ProductMedia.ListMedias:output_type -> productmedia.v1.ListMediasResponse
	10, // 13: productmedia.v1.ProductMedia.DeleteMedia:output_type -> productmedia.v1.DeleteMediaResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_productmedia_v1_product_media_proto_init() }
func file_productmedia_v1_product_media_proto_init() {
	if File_productmedia_v1_product_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_productmedia_v1_product_media_proto_rawDesc), len(file_productmedia_v1_product_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_productmedia_v1_product_media_proto_goTypes,
		DependencyIndexes: file_productmedia_v1_product_media_proto_depIdxs,
		MessageInfos:      file_productmedia_v1_product_media_proto_msgTypes,
	}.Build()
	File_productmedia_v1_product_media_proto = out.File
	file_productmedia_v1_product_media_proto_goTypes = nil
	file_productmedia_v1_product_media_proto_depIdxs = nil
}
