// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: order/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_ORDER_NOT_FOUND      ErrorReason = 0
	ErrorReason_ORDER_STATUS_INVALID ErrorReason = 1
	ErrorReason_ORDER_CANCEL_FAILED  ErrorReason = 2
	ErrorReason_ORDER_CREATE_FAILED  ErrorReason = 3
	ErrorReason_INSUFFICIENT_STOCK   ErrorReason = 4
	ErrorReason_PARAMETER_ERROR      ErrorReason = 5
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ORDER_NOT_FOUND",
		1: "ORDER_STATUS_INVALID",
		2: "ORDER_CANCEL_FAILED",
		3: "ORDER_CREATE_FAILED",
		4: "INSUFFICIENT_STOCK",
		5: "PARAMETER_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"ORDER_NOT_FOUND":      0,
		"ORDER_STATUS_INVALID": 1,
		"ORDER_CANCEL_FAILED":  2,
		"ORDER_CREATE_FAILED":  3,
		"INSUFFICIENT_STOCK":   4,
		"PARAMETER_ERROR":      5,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_order_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_order_v1_error_reason_proto protoreflect.FileDescriptor

const file_order_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1border/v1/error_reason.proto\x12\border.v1*\x9b\x01\n" +
	"\vErrorReason\x12\x13\n" +
	"\x0fORDER_NOT_FOUND\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_INVALID\x10\x01\x12\x17\n" +
	"\x13ORDER_CANCEL_FAILED\x10\x02\x12\x17\n" +
	"\x13ORDER_CREATE_FAILED\x10\x03\x12\x16\n" +
	"\x12INSUFFICIENT_STOCK\x10\x04\x12\x13\n" +
	"\x0fPARAMETER_ERROR\x10\x05B\x17Z\x15order/api/order/v1;v1b\x06proto3"

var (
	file_order_v1_error_reason_proto_rawDescOnce sync.Once
	file_order_v1_error_reason_proto_rawDescData []byte
)

func file_order_v1_error_reason_proto_rawDescGZIP() []byte {
	file_order_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_order_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_error_reason_proto_rawDesc), len(file_order_v1_error_reason_proto_rawDesc)))
	})
	return file_order_v1_error_reason_proto_rawDescData
}

var file_order_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: order.v1.ErrorReason
}
var file_order_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_v1_error_reason_proto_init() }
func file_order_v1_error_reason_proto_init() {
	if File_order_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_error_reason_proto_rawDesc), len(file_order_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_order_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_order_v1_error_reason_proto_enumTypes,
	}.Build()
	File_order_v1_error_reason_proto = out.File
	file_order_v1_error_reason_proto_goTypes = nil
	file_order_v1_error_reason_proto_depIdxs = nil
}
