// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: sku/v1/sku.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SKU实体
type SkuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`                     // 规格串，如 "红色;XL"
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                 // SKU标题
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`                // 分
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`                // 库存
	ImgUrl        string                 `protobuf:"bytes,7,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"` // SKU主图
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"` // 版本号（乐观锁）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkuInfo) Reset() {
	*x = SkuInfo{}
	mi := &file_sku_v1_sku_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuInfo) ProtoMessage() {}

func (x *SkuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuInfo.ProtoReflect.Descriptor instead.
func (*SkuInfo) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{0}
}

func (x *SkuInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SkuInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SkuInfo) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *SkuInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SkuInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SkuInfo) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *SkuInfo) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *SkuInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SkuInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SkuInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// 创建SKU
type CreateSkuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	ImgUrl        string                 `protobuf:"bytes,6,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkuRequest) Reset() {
	*x = CreateSkuRequest{}
	mi := &file_sku_v1_sku_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkuRequest) ProtoMessage() {}

func (x *CreateSkuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkuRequest.ProtoReflect.Descriptor instead.
func (*CreateSkuRequest) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSkuRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateSkuRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateSkuRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSkuRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSkuRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateSkuRequest) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

type CreateSkuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           *SkuInfo               `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkuResponse) Reset() {
	*x = CreateSkuResponse{}
	mi := &file_sku_v1_sku_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkuResponse) ProtoMessage() {}

func (x *CreateSkuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkuResponse.ProtoReflect.Descriptor instead.
func (*CreateSkuResponse) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSkuResponse) GetSku() *SkuInfo {
	if x != nil {
		return x.Sku
	}
	return nil
}

// 更新SKU
type UpdateSkuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	ImgUrl        string                 `protobuf:"bytes,7,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkuRequest) Reset() {
	*x = UpdateSkuRequest{}
	mi := &file_sku_v1_sku_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkuRequest) ProtoMessage() {}

func (x *UpdateSkuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkuRequest.ProtoReflect.Descriptor instead.
func (*UpdateSkuRequest) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSkuRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSkuRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateSkuRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *UpdateSkuRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSkuRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateSkuRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateSkuRequest) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

type UpdateSkuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           *SkuInfo               `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkuResponse) Reset() {
	*x = UpdateSkuResponse{}
	mi := &file_sku_v1_sku_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkuResponse) ProtoMessage() {}

func (x *UpdateSkuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkuResponse.ProtoReflect.Descriptor instead.
func (*UpdateSkuResponse) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSkuResponse) GetSku() *SkuInfo {
	if x != nil {
		return x.Sku
	}
	return nil
}

// 查看SKU详情
type GetSkuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkuRequest) Reset() {
	*x = GetSkuRequest{}
	mi := &file_sku_v1_sku_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkuRequest) ProtoMessage() {}

func (x *GetSkuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkuRequest.ProtoReflect.Descriptor instead.
func (*GetSkuRequest) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{5}
}

func (x *GetSkuRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSkuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           *SkuInfo               `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkuResponse) Reset() {
	*x = GetSkuResponse{}
	mi := &file_sku_v1_sku_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkuResponse) ProtoMessage() {}

func (x *GetSkuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkuResponse.ProtoReflect.Descriptor instead.
func (*GetSkuResponse) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{6}
}

func (x *GetSkuResponse) GetSku() *SkuInfo {
	if x != nil {
		return x.Sku
	}
	return nil
}

// 分页查询SKU列表
type ListSkusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                            // 页码，默认 1
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`    // 每页条数，默认 10
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // 按商品筛选（0=全部）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkusRequest) Reset() {
	*x = ListSkusRequest{}
	mi := &file_sku_v1_sku_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkusRequest) ProtoMessage() {}

func (x *ListSkusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkusRequest.ProtoReflect.Descriptor instead.
func (*ListSkusRequest) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{7}
}

func (x *ListSkusRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSkusRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSkusRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ListSkusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skus          []*SkuInfo             `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkusResponse) Reset() {
	*x = ListSkusResponse{}
	mi := &file_sku_v1_sku_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkusResponse) ProtoMessage() {}

func (x *ListSkusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkusResponse.ProtoReflect.Descriptor instead.
func (*ListSkusResponse) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{8}
}

func (x *ListSkusResponse) GetSkus() []*SkuInfo {
	if x != nil {
		return x.Skus
	}
	return nil
}

func (x *ListSkusResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListSkusResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSkusResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 删除SKU
type DeleteSkuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkuRequest) Reset() {
	*x = DeleteSkuRequest{}
	mi := &file_sku_v1_sku_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkuRequest) ProtoMessage() {}

func (x *DeleteSkuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkuRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkuRequest) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSkuRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSkuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkuResponse) Reset() {
	*x = DeleteSkuResponse{}
	mi := &file_sku_v1_sku_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkuResponse) ProtoMessage() {}

func (x *DeleteSkuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkuResponse.ProtoReflect.Descriptor instead.
func (*DeleteSkuResponse) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSkuResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 扣减库存
type DeductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // 当前版本号，用于乐观锁
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockRequest) Reset() {
	*x = DeductStockRequest{}
	mi := &file_sku_v1_sku_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockRequest) ProtoMessage() {}

func (x *DeductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockRequest.ProtoReflect.Descriptor instead.
func (*DeductStockRequest) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{11}
}

func (x *DeductStockRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeductStockRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *DeductStockRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeductStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewStock      int64                  `protobuf:"varint,2,opt,name=new_stock,json=newStock,proto3" json:"new_stock,omitempty"`
	NewVersion    int64                  `protobuf:"varint,3,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"` // 新版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockResponse) Reset() {
	*x = DeductStockResponse{}
	mi := &file_sku_v1_sku_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockResponse) ProtoMessage() {}

func (x *DeductStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockResponse.ProtoReflect.Descriptor instead.
func (*DeductStockResponse) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{12}
}

func (x *DeductStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeductStockResponse) GetNewStock() int64 {
	if x != nil {
		return x.NewStock
	}
	return 0
}

func (x *DeductStockResponse) GetNewVersion() int64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

// 回补库存
type RestoreStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreStockRequest) Reset() {
	*x = RestoreStockRequest{}
	mi := &file_sku_v1_sku_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStockRequest) ProtoMessage() {}

func (x *RestoreStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStockRequest.ProtoReflect.Descriptor instead.
func (*RestoreStockRequest) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{13}
}

func (x *RestoreStockRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RestoreStockRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RestoreStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewStock      int64                  `protobuf:"varint,2,opt,name=new_stock,json=newStock,proto3" json:"new_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreStockResponse) Reset() {
	*x = RestoreStockResponse{}
	mi := &file_sku_v1_sku_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStockResponse) ProtoMessage() {}

func (x *RestoreStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sku_v1_sku_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStockResponse.ProtoReflect.Descriptor instead.
func (*RestoreStockResponse) Descriptor() ([]byte, []int) {
	return file_sku_v1_sku_proto_rawDescGZIP(), []int{14}
}

func (x *RestoreStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreStockResponse) GetNewStock() int64 {
	if x != nil {
		return x.NewStock
	}
	return 0
}

var File_sku_v1_sku_proto protoreflect.FileDescriptor

const file_sku_v1_sku_proto_rawDesc = "" +
	"\n" +
	"\x10sku/v1/sku.proto\x12\x06sku.v1\x1a\x1cgoogle/api/annotations.proto\"\xfd\x01\n" +
	"\aSkuInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\x12\x17\n" +
	"\aimg_url\x18\a \x01(\tR\x06imgUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\"\x9e\x01\n" +
	"\x10CreateSkuRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x03R\x05stock\x12\x17\n" +
	"\aimg_url\x18\x06 \x01(\tR\x06imgUrl\"6\n" +
	"\x11CreateSkuResponse\x12!\n" +
	"\x03sku\x18\x01 \x01(\v2\x0f.sku.v1.SkuInfoR\x03sku\"\xae\x01\n" +
	"\x10UpdateSkuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\x12\x17\n" +
	"\aimg_url\x18\a \x01(\tR\x06imgUrl\"6\n" +
	"\x11UpdateSkuResponse\x12!\n" +
	"\x03sku\x18\x01 \x01(\v2\x0f.sku.v1.SkuInfoR\x03sku\"\x1f\n" +
	"\rGetSkuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"3\n" +
	"\x0eGetSkuResponse\x12!\n" +
	"\x03sku\x18\x01 \x01(\v2\x0f.sku.v1.SkuInfoR\x03sku\"a\n" +
	"\x0fListSkusRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\"~\n" +
	"\x10ListSkusResponse\x12#\n" +
	"\x04skus\x18\x01 \x03(\v2\x0f.sku.v1.SkuInfoR\x04skus\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\"\n" +
	"\x10DeleteSkuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"-\n" +
	"\x11DeleteSkuResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Z\n" +
	"\x12DeductStockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"m\n" +
	"\x13DeductStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tnew_stock\x18\x02 \x01(\x03R\bnewStock\x12\x1f\n" +
	"\vnew_version\x18\x03 \x01(\x03R\n" +
	"newVersion\"A\n" +
	"\x13RestoreStockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"M\n" +
	"\x14RestoreStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tnew_stock\x18\x02 \x01(\x03R\bnewStock2\xa4\x05\n" +
	"\x03Sku\x12Y\n" +
	"\tCreateSku\x12\x18.sku.v1.CreateSkuRequest\x1a\x19.sku.v1.CreateSkuResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/skus\x12^\n" +
	"\tUpdateSku\x12\x18.sku.v1.UpdateSkuRequest\x1a\x19.sku.v1.UpdateSkuResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/v1/skus/{id}\x12R\n" +
	"\x06GetSku\x12\x15.sku.v1.GetSkuRequest\x1a\x16.sku.v1.GetSkuResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/skus/{id}\x12S\n" +
	"\bListSkus\x12\x17.sku.v1.ListSkusRequest\x1a\x18.sku.v1.ListSkusResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/skus\x12[\n" +
	"\tDeleteSku\x12\x18.sku.v1.DeleteSkuRequest\x1a\x19.sku.v1.DeleteSkuResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/v1/skus/{id}\x12k\n" +
	"\vDeductStock\x12\x1a.sku.v1.DeductStockRequest\x1a\x1b.sku.v1.DeductStockResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/skus/{id}/deduct\x12o\n" +
	"\fRestoreStock\x12\x1b.sku.v1.RestoreStockRequest\x1a\x1c.sku.v1.RestoreStockResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/skus/{id}/restoreB\x1dZ\x1bproductCenter/api/sku/v1;v1b\x06proto3"

var (
	file_sku_v1_sku_proto_rawDescOnce sync.Once
	file_sku_v1_sku_proto_rawDescData []byte
)

func file_sku_v1_sku_proto_rawDescGZIP() []byte {
	file_sku_v1_sku_proto_rawDescOnce.Do(func() {
		file_sku_v1_sku_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sku_v1_sku_proto_rawDesc), len(file_sku_v1_sku_proto_rawDesc)))
	})
	return file_sku_v1_sku_proto_rawDescData
}

var file_sku_v1_sku_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_sku_v1_sku_proto_goTypes = []any{
	(*SkuInfo)(nil),              // 0: sku.v1.SkuInfo
	(*CreateSkuRequest)(nil),     // 1: sku.v1.CreateSkuRequest
	(*CreateSkuResponse)(nil),    // 2: sku.v1.CreateSkuResponse
	(*UpdateSkuRequest)(nil),     // 3: sku.v1.UpdateSkuRequest
	(*UpdateSkuResponse)(nil),    // 4: sku.v1.UpdateSkuResponse
	(*GetSkuRequest)(nil),        // 5: sku.v1.GetSkuRequest
	(*GetSkuResponse)(nil),       // 6: sku.v1.GetSkuResponse
	(*ListSkusRequest)(nil),      // 7: sku.v1.ListSkusRequest
	(*ListSkusResponse)(nil),     // 8: sku.v1.ListSkusResponse
	(*DeleteSkuRequest)(nil),     // 9: sku.v1.DeleteSkuRequest
	(*DeleteSkuResponse)(nil),    // 10: sku.v1.DeleteSkuResponse
	(*DeductStockRequest)(nil),   // 11: sku.v1.DeductStockRequest
	(*DeductStockResponse)(nil),  // 12: sku.v1.DeductStockResponse
	(*RestoreStockRequest)(nil),  // 13: sku.v1.RestoreStockRequest
	(*RestoreStockResponse)(nil), // 14: sku.v1.RestoreStockResponse
}
var file_sku_v1_sku_proto_depIdxs = []int32{
	0,  // 0: sku.v1.CreateSkuResponse.sku:type_name -> sku.v1.SkuInfo
	0,  // 1: sku.v1.UpdateSkuResponse.sku:type_name -> sku.v1.SkuInfo
	0,  // 2: sku.v1.GetSkuResponse.sku:type_name -> sku.v1.SkuInfo
	0,  // 3: sku.v1.ListSkusResponse.skus:type_name -> sku.v1.SkuInfo
	1,  // 4: sku.v1.Sku.CreateSku:input_type -> sku.v1.CreateSkuRequest
	3,  // 5: sku.v1.Sku.UpdateSku:input_type -> sku.v1.UpdateSkuRequest
	5,  // 6: sku.v1.Sku.GetSku:input_type -> sku.v1.GetSkuRequest
	7,  // 7: sku.v1.Sku.ListSkus:input_type -> sku.v1.ListSkusRequest
	9,  // 8: sku.v1.Sku.DeleteSku:input_type -> sku.v1.DeleteSkuRequest
	11, // 9: sku.v1.Sku.DeductStock:input_type -> sku.v1.DeductStockRequest
	13, // 10: sku.v1.Sku.RestoreStock:input_type -> sku.v1.RestoreStockRequest
	2,  // 11: sku.v1.Sku.CreateSku:output_type -> sku.v1.CreateSkuResponse
	4,  // 12: sku.v1.Sku.UpdateSku:output_type -> sku.v1.UpdateSkuResponse
	6,  // 13: sku.v1.Sku.GetSku:output_type -> sku.v1.GetSkuResponse
	8,  // 14: sku.v1.Sku.ListSkus:output_type -> sku.v1.ListSkusResponse
	10, // 15: sku.v1.Sku.DeleteSku:output_type -> sku.v1.DeleteSkuResponse
	12, // 16: sku.v1.Sku.DeductStock:output_type -> sku.v1.DeductStockResponse
	14, // 17: sku.v1.Sku.RestoreStock:output_type -> sku.v1.RestoreStockResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_sku_v1_sku_proto_init() }
func file_sku_v1_sku_proto_init() {
	if File_sku_v1_sku_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sku_v1_sku_proto_rawDesc), len(file_sku_v1_sku_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sku_v1_sku_proto_goTypes,
		DependencyIndexes: file_sku_v1_sku_proto_depIdxs,
		MessageInfos:      file_sku_v1_sku_proto_msgTypes,
	}.Build()
	File_sku_v1_sku_proto = out.File
	file_sku_v1_sku_proto_goTypes = nil
	file_sku_v1_sku_proto_depIdxs = nil
}
