// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: sku/v1/sku.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sku_CreateSku_FullMethodName    = "/sku.v1.Sku/CreateSku"
	Sku_UpdateSku_FullMethodName    = "/sku.v1.Sku/UpdateSku"
	Sku_GetSku_FullMethodName       = "/sku.v1.Sku/GetSku"
	Sku_ListSkus_FullMethodName     = "/sku.v1.Sku/ListSkus"
	Sku_DeleteSku_FullMethodName    = "/sku.v1.Sku/DeleteSku"
	Sku_DeductStock_FullMethodName  = "/sku.v1.Sku/DeductStock"
	Sku_RestoreStock_FullMethodName = "/sku.v1.Sku/RestoreStock"
)

// SkuClient is the client API for Sku service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 商品SKU服务
type SkuClient interface {
	// 创建SKU
	CreateSku(ctx context.Context, in *CreateSkuRequest, opts ...grpc.CallOption) (*CreateSkuResponse, error)
	// 更新SKU
	UpdateSku(ctx context.Context, in *UpdateSkuRequest, opts ...grpc.CallOption) (*UpdateSkuResponse, error)
	// 查看SKU详情
	GetSku(ctx context.Context, in *GetSkuRequest, opts ...grpc.CallOption) (*GetSkuResponse, error)
	// 分页查询SKU列表（支持按商品筛选）
	ListSkus(ctx context.Context, in *ListSkusRequest, opts ...grpc.CallOption) (*ListSkusResponse, error)
	// 删除SKU
	DeleteSku(ctx context.Context, in *DeleteSkuRequest, opts ...grpc.CallOption) (*DeleteSkuResponse, error)
	// 扣减库存（乐观锁）
	DeductStock(ctx context.Context, in *DeductStockRequest, opts ...grpc.CallOption) (*DeductStockResponse, error)
	// 回补库存
	RestoreStock(ctx context.Context, in *RestoreStockRequest, opts ...grpc.CallOption) (*RestoreStockResponse, error)
}

type skuClient struct {
	cc grpc.ClientConnInterface
}

func NewSkuClient(cc grpc.ClientConnInterface) SkuClient {
	return &skuClient{cc}
}

func (c *skuClient) CreateSku(ctx context.Context, in *CreateSkuRequest, opts ...grpc.CallOption) (*CreateSkuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSkuResponse)
	err := c.cc.Invoke(ctx, Sku_CreateSku_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuClient) UpdateSku(ctx context.Context, in *UpdateSkuRequest, opts ...grpc.CallOption) (*UpdateSkuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSkuResponse)
	err := c.cc.Invoke(ctx, Sku_UpdateSku_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuClient) GetSku(ctx context.Context, in *GetSkuRequest, opts ...grpc.CallOption) (*GetSkuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkuResponse)
	err := c.cc.Invoke(ctx, Sku_GetSku_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuClient) ListSkus(ctx context.Context, in *ListSkusRequest, opts ...grpc.CallOption) (*ListSkusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkusResponse)
	err := c.cc.Invoke(ctx, Sku_ListSkus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuClient) DeleteSku(ctx context.Context, in *DeleteSkuRequest, opts ...grpc.CallOption) (*DeleteSkuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSkuResponse)
	err := c.cc.Invoke(ctx, Sku_DeleteSku_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuClient) DeductStock(ctx context.Context, in *DeductStockRequest, opts ...grpc.CallOption) (*DeductStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductStockResponse)
	err := c.cc.Invoke(ctx, Sku_DeductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuClient) RestoreStock(ctx context.Context, in *RestoreStockRequest, opts ...grpc.CallOption) (*RestoreStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreStockResponse)
	err := c.cc.Invoke(ctx, Sku_RestoreStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkuServer is the server API for Sku service.
// All implementations must embed UnimplementedSkuServer
// for forward compatibility.
//
// 商品SKU服务
type SkuServer interface {
	// 创建SKU
	CreateSku(context.Context, *CreateSkuRequest) (*CreateSkuResponse, error)
	// 更新SKU
	UpdateSku(context.Context, *UpdateSkuRequest) (*UpdateSkuResponse, error)
	// 查看SKU详情
	GetSku(context.Context, *GetSkuRequest) (*GetSkuResponse, error)
	// 分页查询SKU列表（支持按商品筛选）
	ListSkus(context.Context, *ListSkusRequest) (*ListSkusResponse, error)
	// 删除SKU
	DeleteSku(context.Context, *DeleteSkuRequest) (*DeleteSkuResponse, error)
	// 扣减库存（乐观锁）
	DeductStock(context.Context, *DeductStockRequest) (*DeductStockResponse, error)
	// 回补库存
	RestoreStock(context.Context, *RestoreStockRequest) (*RestoreStockResponse, error)
	mustEmbedUnimplementedSkuServer()
}

// UnimplementedSkuServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkuServer struct{}

func (UnimplementedSkuServer) CreateSku(context.Context, *CreateSkuRequest) (*CreateSkuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSku not implemented")
}
func (UnimplementedSkuServer) UpdateSku(context.Context, *UpdateSkuRequest) (*UpdateSkuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSku not implemented")
}
func (UnimplementedSkuServer) GetSku(context.Context, *GetSkuRequest) (*GetSkuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSku not implemented")
}
func (UnimplementedSkuServer) ListSkus(context.Context, *ListSkusRequest) (*ListSkusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSkus not implemented")
}
func (UnimplementedSkuServer) DeleteSku(context.Context, *DeleteSkuRequest) (*DeleteSkuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSku not implemented")
}
func (UnimplementedSkuServer) DeductStock(context.Context, *DeductStockRequest) (*DeductStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeductStock not implemented")
}
func (UnimplementedSkuServer) RestoreStock(context.Context, *RestoreStockRequest) (*RestoreStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreStock not implemented")
}
func (UnimplementedSkuServer) mustEmbedUnimplementedSkuServer() {}
func (UnimplementedSkuServer) testEmbeddedByValue()             {}

// UnsafeSkuServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkuServer will
// result in compilation errors.
type UnsafeSkuServer interface {
	mustEmbedUnimplementedSkuServer()
}

func RegisterSkuServer(s grpc.ServiceRegistrar, srv SkuServer) {
	// If the following call pancis, it indicates UnimplementedSkuServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sku_ServiceDesc, srv)
}

func _Sku_CreateSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSkuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServer).CreateSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sku_CreateSku_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServer).CreateSku(ctx, req.(*CreateSkuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sku_UpdateSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSkuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServer).UpdateSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sku_UpdateSku_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServer).UpdateSku(ctx, req.(*UpdateSkuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sku_GetSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServer).GetSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sku_GetSku_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServer).GetSku(ctx, req.(*GetSkuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sku_ListSkus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServer).ListSkus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sku_ListSkus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServer).ListSkus(ctx, req.(*ListSkusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sku_DeleteSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSkuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServer).DeleteSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sku_DeleteSku_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServer).DeleteSku(ctx, req.(*DeleteSkuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sku_DeductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServer).DeductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sku_DeductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServer).DeductStock(ctx, req.(*DeductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sku_RestoreStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServer).RestoreStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sku_RestoreStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServer).RestoreStock(ctx, req.(*RestoreStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sku_ServiceDesc is the grpc.ServiceDesc for Sku service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sku_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sku.v1.Sku",
	HandlerType: (*SkuServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSku",
			Handler:    _Sku_CreateSku_Handler,
		},
		{
			MethodName: "UpdateSku",
			Handler:    _Sku_UpdateSku_Handler,
		},
		{
			MethodName: "GetSku",
			Handler:    _Sku_GetSku_Handler,
		},
		{
			MethodName: "ListSkus",
			Handler:    _Sku_ListSkus_Handler,
		},
		{
			MethodName: "DeleteSku",
			Handler:    _Sku_DeleteSku_Handler,
		},
		{
			MethodName: "DeductStock",
			Handler:    _Sku_DeductStock_Handler,
		},
		{
			MethodName: "RestoreStock",
			Handler:    _Sku_RestoreStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sku/v1/sku.proto",
}
