// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.0
// source: producttag/v1/product_tag.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProductTagCreateTag = "/producttag.v1.ProductTag/CreateTag"
const OperationProductTagDeleteTag = "/producttag.v1.ProductTag/DeleteTag"
const OperationProductTagGetTag = "/producttag.v1.ProductTag/GetTag"
const OperationProductTagListTags = "/producttag.v1.ProductTag/ListTags"
const OperationProductTagUpdateTag = "/producttag.v1.ProductTag/UpdateTag"

type ProductTagHTTPServer interface {
	// CreateTag 创建标签
	CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	// DeleteTag 删除标签
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	// GetTag 查看标签详情
	GetTag(context.Context, *GetTagRequest) (*GetTagResponse, error)
	// ListTags 分页查询标签列表
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	// UpdateTag 更新标签
	UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error)
}

func RegisterProductTagHTTPServer(s *http.Server, srv ProductTagHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/tags", _ProductTag_CreateTag0_HTTP_Handler(srv))
	r.PUT("/api/v1/tags/{id}", _ProductTag_UpdateTag0_HTTP_Handler(srv))
	r.GET("/api/v1/tags/{id}", _ProductTag_GetTag0_HTTP_Handler(srv))
	r.GET("/api/v1/tags", _ProductTag_ListTags0_HTTP_Handler(srv))
	r.DELETE("/api/v1/tags/{id}", _ProductTag_DeleteTag0_HTTP_Handler(srv))
}

func _ProductTag_CreateTag0_HTTP_Handler(srv ProductTagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductTagCreateTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTag(ctx, req.(*CreateTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTagResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductTag_UpdateTag0_HTTP_Handler(srv ProductTagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductTagUpdateTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTag(ctx, req.(*UpdateTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateTagResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductTag_GetTag0_HTTP_Handler(srv ProductTagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTagRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductTagGetTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTag(ctx, req.(*GetTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTagResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductTag_ListTags0_HTTP_Handler(srv ProductTagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTagsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductTagListTags)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTags(ctx, req.(*ListTagsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTagsResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductTag_DeleteTag0_HTTP_Handler(srv ProductTagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTagRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductTagDeleteTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTag(ctx, req.(*DeleteTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteTagResponse)
		return ctx.Result(200, reply)
	}
}

type ProductTagHTTPClient interface {
	// CreateTag 创建标签
	CreateTag(ctx context.Context, req *CreateTagRequest, opts ...http.CallOption) (rsp *CreateTagResponse, err error)
	// DeleteTag 删除标签
	DeleteTag(ctx context.Context, req *DeleteTagRequest, opts ...http.CallOption) (rsp *DeleteTagResponse, err error)
	// GetTag 查看标签详情
	GetTag(ctx context.Context, req *GetTagRequest, opts ...http.CallOption) (rsp *GetTagResponse, err error)
	// ListTags 分页查询标签列表
	ListTags(ctx context.Context, req *ListTagsRequest, opts ...http.CallOption) (rsp *ListTagsResponse, err error)
	// UpdateTag 更新标签
	UpdateTag(ctx context.Context, req *UpdateTagRequest, opts ...http.CallOption) (rsp *UpdateTagResponse, err error)
}

type ProductTagHTTPClientImpl struct {
	cc *http.Client
}

func NewProductTagHTTPClient(client *http.Client) ProductTagHTTPClient {
	return &ProductTagHTTPClientImpl{client}
}

// CreateTag 创建标签
func (c *ProductTagHTTPClientImpl) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...http.CallOption) (*CreateTagResponse, error) {
	var out CreateTagResponse
	pattern := "/api/v1/tags"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductTagCreateTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteTag 删除标签
func (c *ProductTagHTTPClientImpl) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...http.CallOption) (*DeleteTagResponse, error) {
	var out DeleteTagResponse
	pattern := "/api/v1/tags/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductTagDeleteTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTag 查看标签详情
func (c *ProductTagHTTPClientImpl) GetTag(ctx context.Context, in *GetTagRequest, opts ...http.CallOption) (*GetTagResponse, error) {
	var out GetTagResponse
	pattern := "/api/v1/tags/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductTagGetTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTags 分页查询标签列表
func (c *ProductTagHTTPClientImpl) ListTags(ctx context.Context, in *ListTagsRequest, opts ...http.CallOption) (*ListTagsResponse, error) {
	var out ListTagsResponse
	pattern := "/api/v1/tags"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductTagListTags))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTag 更新标签
func (c *ProductTagHTTPClientImpl) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...http.CallOption) (*UpdateTagResponse, error) {
	var out UpdateTagResponse
	pattern := "/api/v1/tags/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductTagUpdateTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
