// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: producttag/v1/product_tag.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 标签实体
type TagInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagInfo) Reset() {
	*x = TagInfo{}
	mi := &file_producttag_v1_product_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagInfo) ProtoMessage() {}

func (x *TagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_producttag_v1_product_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagInfo.ProtoReflect.Descriptor instead.
func (*TagInfo) Descriptor() ([]byte, []int) {
	return file_producttag_v1_product_tag_proto_rawDescGZIP(), []int{0}
}

func (x *TagInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagInfo) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *TagInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TagInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 创建标签
type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sort          int32                  `protobuf:"varint,2,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_producttag_v1_product_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_producttag_v1_product_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_producttag_v1_product_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTagRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type CreateTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *TagInfo               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagResponse) Reset() {
	*x = CreateTagResponse{}
	mi := &file_producttag_v1_product_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagResponse) ProtoMessage() {}

func (x *CreateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_producttag_v1_product_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagResponse.ProtoReflect.Descriptor instead.
func (*CreateTagResponse) Descriptor() ([]byte, []int) {
	return file_producttag_v1_product_tag_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTagResponse) GetTag() *TagInfo {
	if x != nil {
		return x.Tag
	}
	return nil
}

// 更新标签
type UpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_producttag_v1_product_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_producttag_v1_product_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_producttag_v1_product_tag_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTagRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTagRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type UpdateTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *TagInfo               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagResponse) Reset() {
	*x = UpdateTagResponse{}
	mi := &file_producttag_v1_product_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagResponse) ProtoMessage() {}

func (x *UpdateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_producttag_v1_product_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagResponse.ProtoReflect.Descriptor instead.
func (*UpdateTagResponse) Descriptor() ([]byte, []int) {
	return file_producttag_v1_product_tag_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTagResponse) GetTag() *TagInfo {
	if x != nil {
		return x.Tag
	}
	return nil
}

// 查看标签详情
type GetTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagRequest) Reset() {
	*x = GetTagRequest{}
	mi := &file_producttag_v1_product_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagRequest) ProtoMessage() {}

func (x *GetTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_producttag_v1_product_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagRequest.ProtoReflect.Descriptor instead.
func (*GetTagRequest) Descriptor() ([]byte, []int) {
	return file_producttag_v1_product_tag_proto_rawDescGZIP(), []int{5}
}

func (x *GetTagRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *TagInfo               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagResponse) Reset() {
	*x = GetTagResponse{}
	mi := &file_producttag_v1_product_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagResponse) ProtoMessage() {}

func (x *GetTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_producttag_v1_product_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagResponse.ProtoReflect.Descriptor instead.
func (*GetTagResponse) Descriptor() ([]byte, []int) {
	return file_producttag_v1_product_tag_proto_rawDescGZIP(), []int{6}
}

func (x *GetTagResponse) GetTag() *TagInfo {
	if x != nil {
		return x.Tag
	}
	return nil
}

// 分页查询标签列表
type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码，默认 1
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数，默认 10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_producttag_v1_product_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_producttag_v1_product_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_producttag_v1_product_tag_proto_rawDescGZIP(), []int{7}
}

func (x *ListTagsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTagsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*TagInfo             `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_producttag_v1_product_tag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_producttag_v1_product_tag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_producttag_v1_product_tag_proto_rawDescGZIP(), []int{8}
}

func (x *ListTagsResponse) GetTags() []*TagInfo {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListTagsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTagsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTagsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 删除标签
type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_producttag_v1_product_tag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_producttag_v1_product_tag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_producttag_v1_product_tag_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTagRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	mi := &file_producttag_v1_product_tag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_producttag_v1_product_tag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_producttag_v1_product_tag_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTagResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_producttag_v1_product_tag_proto protoreflect.FileDescriptor

const file_producttag_v1_product_tag_proto_rawDesc = "" +
	"\n" +
	"\x1fproducttag/v1/product_tag.proto\x12\rproducttag.v1\x1a\x1cgoogle/api/annotations.proto\"\x7f\n" +
	"\aTagInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\":\n" +
	"\x10CreateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\x05R\x04sort\"=\n" +
	"\x11CreateTagResponse\x12(\n" +
	"\x03tag\x18\x01 \x01(\v2\x16.producttag.v1.TagInfoR\x03tag\"J\n" +
	"\x10UpdateTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\"=\n" +
	"\x11UpdateTagResponse\x12(\n" +
	"\x03tag\x18\x01 \x01(\v2\x16.producttag.v1.TagInfoR\x03tag\"\x1f\n" +
	"\rGetTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\":\n" +
	"\x0eGetTagResponse\x12(\n" +
	"\x03tag\x18\x01 \x01(\v2\x16.producttag.v1.TagInfoR\x03tag\"B\n" +
	"\x0fListTagsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x85\x01\n" +
	"\x10ListTagsResponse\x12*\n" +
	"\x04tags\x18\x01 \x03(\v2\x16.producttag.v1.TagInfoR\x04tags\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\"\n" +
	"\x10DeleteTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"-\n" +
	"\x11DeleteTagResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x93\x04\n" +
	"\n" +
	"ProductTag\x12g\n" +
	"\tCreateTag\x12\x1f.producttag.v1.CreateTagRequest\x1a .producttag.v1.CreateTagResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/tags\x12l\n" +
	"\tUpdateTag\x12\x1f.producttag.v1.UpdateTagRequest\x1a .producttag.v1.UpdateTagResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/v1/tags/{id}\x12`\n" +
	"\x06GetTag\x12\x1c.producttag.v1.GetTagRequest\x1a\x1d.producttag.v1.GetTagResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/tags/{id}\x12a\n" +
	"\bListTags\x12\x1e.producttag.v1.ListTagsRequest\x1a\x1f.producttag.v1.ListTagsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/tags\x12i\n" +
	"\tDeleteTag\x12\x1f.producttag.v1.DeleteTagRequest\x1a .producttag.v1.DeleteTagResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/v1/tags/{id}B$Z\"productCenter/api/producttag/v1;v1b\x06proto3"

var (
	file_producttag_v1_product_tag_proto_rawDescOnce sync.Once
	file_producttag_v1_product_tag_proto_rawDescData []byte
)

func file_producttag_v1_product_tag_proto_rawDescGZIP() []byte {
	file_producttag_v1_product_tag_proto_rawDescOnce.Do(func() {
		file_producttag_v1_product_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_producttag_v1_product_tag_proto_rawDesc), len(file_producttag_v1_product_tag_proto_rawDesc)))
	})
	return file_producttag_v1_product_tag_proto_rawDescData
}

var file_producttag_v1_product_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_producttag_v1_product_tag_proto_goTypes = []any{
	(*TagInfo)(nil),           // 0: producttag.v1.TagInfo
	(*CreateTagRequest)(nil),  // 1: producttag.v1.CreateTagRequest
	(*CreateTagResponse)(nil), // 2: producttag.v1.CreateTagResponse
	(*UpdateTagRequest)(nil),  // 3: producttag.v1.UpdateTagRequest
	(*UpdateTagResponse)(nil), // 4: producttag.v1.UpdateTagResponse
	(*GetTagRequest)(nil),     // 5: producttag.v1.GetTagRequest
	(*GetTagResponse)(nil),    // 6: producttag.v1.GetTagResponse
	(*ListTagsRequest)(nil),   // 7: producttag.v1.ListTagsRequest
	(*ListTagsResponse)(nil),  // 8: producttag.v1.ListTagsResponse
	(*DeleteTagRequest)(nil),  // 9: producttag.v1.DeleteTagRequest
	(*DeleteTagResponse)(nil), // 10: producttag.v1.DeleteTagResponse
}
var file_producttag_v1_product_tag_proto_depIdxs = []int32{
	0,  // 0: producttag.v1.CreateTagResponse.tag:type_name -> producttag.v1.TagInfo
	0,  // 1: producttag.v1.UpdateTagResponse.tag:type_name -> producttag.v1.TagInfo
	0,  // 2: producttag.v1.GetTagResponse.tag:type_name -> producttag.v1.TagInfo
	0,  // 3: producttag.v1.ListTagsResponse.tags:type_name -> producttag.v1.TagInfo
	1,  // 4: producttag.v1.ProductTag.CreateTag:input_type -> producttag.v1.CreateTagRequest
	3,  // 5: producttag.v1.ProductTag.UpdateTag:input_type -> producttag.v1.UpdateTagRequest
	5,  // 6: producttag.v1.ProductTag.GetTag:input_type -> producttag.v1.GetTagRequest
	7,  // 7: producttag.v1.ProductTag.ListTags:input_type -> producttag.v1.ListTagsRequest
	9,  // 8: producttag.v1.ProductTag.DeleteTag:input_type -> producttag.v1.DeleteTagRequest
	2,  // 9: producttag.v1.ProductTag.CreateTag:output_type -> producttag.v1.CreateTagResponse
	4,  // 10: producttag.v1.ProductTag.UpdateTag:output_type -> producttag.v1.UpdateTagResponse
	6,  // 11: producttag.v1.ProductTag.GetTag:output_type -> producttag.v1.GetTagResponse
	8,  // 12: producttag.v1.ProductTag.ListTags:output_type -> producttag.v1.ListTagsResponse
	10, // 13: producttag.v1.ProductTag.DeleteTag:output_type -> producttag.v1.DeleteTagResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_producttag_v1_product_tag_proto_init() }
func file_producttag_v1_product_tag_proto_init() {
	if File_producttag_v1_product_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_producttag_v1_product_tag_proto_rawDesc), len(file_producttag_v1_product_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_producttag_v1_product_tag_proto_goTypes,
		DependencyIndexes: file_producttag_v1_product_tag_proto_depIdxs,
		MessageInfos:      file_producttag_v1_product_tag_proto_msgTypes,
	}.Build()
	File_producttag_v1_product_tag_proto = out.File
	file_producttag_v1_product_tag_proto_goTypes = nil
	file_producttag_v1_product_tag_proto_depIdxs = nil
}
