// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bff/internal/biz"
	"bff/internal/conf"
	"bff/internal/data"
	"bff/internal/server"
	"bff/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	bffRepo := data.NewBFFRepo(dataData)
	bffUseCase := biz.NewBFFUseCase(bffRepo, logger)
	bffService := service.NewBFFService(bffUseCase)
	grpcServer := server.NewGRPCServer(confServer, bffService, logger)
	httpServer := server.NewHTTPServer(confServer, bffService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
