// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bff/internal/biz"
	"bff/internal/conf"
	"bff/internal/data"
	"bff/internal/server"
	"bff/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger, registrar registry.Registrar) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, registrar, logger)
	if err != nil {
		return nil, nil, err
	}
	bffRepo := data.NewBFFRepo(dataData, logger)
	bffUseCase := biz.NewBFFUseCase(bffRepo, logger)
	bffService := service.NewBFFService(bffUseCase)
	grpcServer := server.NewGRPCServer(confServer, bffService, logger)
	httpServer := server.NewHTTPServer(confServer, bffService, logger)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
