server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:dtw258989971@tcp(127.0.0.1:3309)/shoptest?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  nacos:
    address: 127.0.0.1:8848
    namespace_id: public
    timeout_ms: 5000
    log_dir: /tmp/nacos/log
    cache_dir: /tmp/nacos/cache
